-- backfill load of history values for customer lifetime features
INSERT INTO retail_fs.customer_lifetime_history
( CUSTOMERID, ASOF_TS, ingest_ts,  CUSTOMER_LIFETIME_ACTIVE_DAYS,CUSTOMER_LIFETIME_QTY,
  CUSTOMER_LIFETIME_ITEMS_PER_ACTIVE_DAY,CUSTOMER_LIFETIME_REVENUE_PER_ACTIVE_DAY,
  CUSTOMER_LIFETIME_DAYS,CUSTOMER_DAYS_SINCE_PURCHASE,
  CUSTOMER_LIFETIME_VALUE, CUSTOMER_START_DATE)
SELECT CUSTOMERID,
       CAST(THEDATE AS TIMESTAMP) ASOF_TS, current_timestamp as ingest_ts,
        ACTIVE_DAYS, LIFETIME_QTY, LIFETIME_ITEMS_PER_ACTIVE_DAY,LIFETIME_REVENUE_PER_ACTIVE_DAY,
        CUSTOMER_LIFETIME_DAYS, CUSTOMER_DAYS_SINCE_PURCHASE, LIFETIME_VALUE, LIFETIME_MIN_DATE
FROM
(
    SELECT x.CUSTOMERID, c.TheDate, ACTIVE_DAYS, LIFETIME_QTY, LIFETIME_ITEMS_PER_ACTIVE_DAY,LIFETIME_REVENUE_PER_ACTIVE_DAY, LIFETIME_VALUE,
           c.TheDate - LIFETIME_MIN_DATE as CUSTOMER_LIFETIME_DAYS, c.TheDate - LIFETIME_MAX_DATE as CUSTOMER_DAYS_SINCE_PURCHASE,
           LIFETIME_MIN_DATE
    FROM
        RETAIL_RFM.CALENDAR c
    INNER JOIN
        (
            SELECT
                CUSTOMERID,
                INVOICEDATE,
                LAST_VALUE(INVOICEDATE) OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) NEXT_INVOICEDATE,
                count(*) OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) ACTIVE_DAYS,
                sum(TOTAL_QTY) OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)  LIFETIME_QTY,
                (sum(TOTAL_QTY) OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) *1.0/count(*)  OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) LIFETIME_ITEMS_PER_ACTIVE_DAY,
                (sum(TOTAL_REVENUE)  OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) *1.0/count(*)  OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) LIFETIME_REVENUE_PER_ACTIVE_DAY,
                min(invoicedate)  OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) LIFETIME_MIN_DATE,
                max(invoicedate)  OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) LIFETIME_MAX_DATE,
                sum(TOTAL_REVENUE)  OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) LIFETIME_VALUE
            FROM RETAIL_RFM.CUSTOMER_CATEGORY_ACTIVITY a --splice-properties splits=50
        )x
        ON c.TheDate BETWEEN x.INVOICEDATE AND x.NEXT_INVOICEDATE-1
)x  --splice-properties useSpark=true
;


INSERT INTO retail_fs.CUSTOMER_RFM_BY_CATEGORY_HISTORY
(
        CUSTOMERID,
        ASOF_TS,
        INGEST_TS,
        CUSTOMER_RFM_CLOTHING_RATE_1W, CUSTOMER_RFM_CLOTHING_RATE_2W, CUSTOMER_RFM_CLOTHING_RATE_4W, CUSTOMER_RFM_CLOTHING_RATE_8W, CUSTOMER_RFM_CLOTHING_RATE_16W, CUSTOMER_RFM_CLOTHING_RATE_32W, CUSTOMER_RFM_CLOTHING_RATE_52W,
        CUSTOMER_RFM_DELICATESSEN_RATE_1W, CUSTOMER_RFM_DELICATESSEN_RATE_2W, CUSTOMER_RFM_DELICATESSEN_RATE_4W, CUSTOMER_RFM_DELICATESSEN_RATE_8W, CUSTOMER_RFM_DELICATESSEN_RATE_16W, CUSTOMER_RFM_DELICATESSEN_RATE_32W, CUSTOMER_RFM_DELICATESSEN_RATE_52W,
        CUSTOMER_RFM_GARDEN_RATE_1W, CUSTOMER_RFM_GARDEN_RATE_2W, CUSTOMER_RFM_GARDEN_RATE_4W, CUSTOMER_RFM_GARDEN_RATE_8W, CUSTOMER_RFM_GARDEN_RATE_16W, CUSTOMER_RFM_GARDEN_RATE_32W, CUSTOMER_RFM_GARDEN_RATE_52W,
        CUSTOMER_RFM_HOME_RATE_1W, CUSTOMER_RFM_HOME_RATE_2W, CUSTOMER_RFM_HOME_RATE_4W, CUSTOMER_RFM_HOME_RATE_8W, CUSTOMER_RFM_HOME_RATE_16W, CUSTOMER_RFM_HOME_RATE_32W, CUSTOMER_RFM_HOME_RATE_52W,
        CUSTOMER_RFM_HOME_DECOR_RATE_1W, CUSTOMER_RFM_HOME_DECOR_RATE_2W, CUSTOMER_RFM_HOME_DECOR_RATE_4W, CUSTOMER_RFM_HOME_DECOR_RATE_8W, CUSTOMER_RFM_HOME_DECOR_RATE_16W, CUSTOMER_RFM_HOME_DECOR_RATE_32W, CUSTOMER_RFM_HOME_DECOR_RATE_52W,
        CUSTOMER_RFM_JEWELRY_RATE_1W, CUSTOMER_RFM_JEWELRY_RATE_2W, CUSTOMER_RFM_JEWELRY_RATE_4W, CUSTOMER_RFM_JEWELRY_RATE_8W, CUSTOMER_RFM_JEWELRY_RATE_16W, CUSTOMER_RFM_JEWELRY_RATE_32W, CUSTOMER_RFM_JEWELRY_RATE_52W,
        CUSTOMER_RFM_KITCHEN_RATE_1W, CUSTOMER_RFM_KITCHEN_RATE_2W, CUSTOMER_RFM_KITCHEN_RATE_4W, CUSTOMER_RFM_KITCHEN_RATE_8W, CUSTOMER_RFM_KITCHEN_RATE_16W, CUSTOMER_RFM_KITCHEN_RATE_32W, CUSTOMER_RFM_KITCHEN_RATE_52W,
        CUSTOMER_RFM_NOVELTY_RATE_1W, CUSTOMER_RFM_NOVELTY_RATE_2W, CUSTOMER_RFM_NOVELTY_RATE_4W, CUSTOMER_RFM_NOVELTY_RATE_8W, CUSTOMER_RFM_NOVELTY_RATE_16W, CUSTOMER_RFM_NOVELTY_RATE_32W, CUSTOMER_RFM_NOVELTY_RATE_52W,
        CUSTOMER_RFM_SCHOOL_SUPPLIES_RATE_1W, CUSTOMER_RFM_SCHOOL_SUPPLIES_RATE_2W, CUSTOMER_RFM_SCHOOL_SUPPLIES_RATE_4W, CUSTOMER_RFM_SCHOOL_SUPPLIES_RATE_8W, CUSTOMER_RFM_SCHOOL_SUPPLIES_RATE_16W, CUSTOMER_RFM_SCHOOL_SUPPLIES_RATE_32W, CUSTOMER_RFM_SCHOOL_SUPPLIES_RATE_52W,
        CUSTOMER_RFM_TOYS_RATE_1W, CUSTOMER_RFM_TOYS_RATE_2W, CUSTOMER_RFM_TOYS_RATE_4W, CUSTOMER_RFM_TOYS_RATE_8W, CUSTOMER_RFM_TOYS_RATE_16W, CUSTOMER_RFM_TOYS_RATE_32W, CUSTOMER_RFM_TOYS_RATE_52W,
        CUSTOMER_RFM_TRAVEL_RATE_1W, CUSTOMER_RFM_TRAVEL_RATE_2W, CUSTOMER_RFM_TRAVEL_RATE_4W, CUSTOMER_RFM_TRAVEL_RATE_8W, CUSTOMER_RFM_TRAVEL_RATE_16W, CUSTOMER_RFM_TRAVEL_RATE_32W, CUSTOMER_RFM_TRAVEL_RATE_52W,
        CUSTOMER_RFM_TOTAL_RATE_1W, CUSTOMER_RFM_TOTAL_RATE_2W, CUSTOMER_RFM_TOTAL_RATE_4W, CUSTOMER_RFM_TOTAL_RATE_8W, CUSTOMER_RFM_TOTAL_RATE_16W, CUSTOMER_RFM_TOTAL_RATE_32W, CUSTOMER_RFM_TOTAL_RATE_52W,

        CUSTOMER_RFM_CLOTHING_REVN_RATE_1W, CUSTOMER_RFM_CLOTHING_REVN_RATE_2W, CUSTOMER_RFM_CLOTHING_REVN_RATE_4W, CUSTOMER_RFM_CLOTHING_REVN_RATE_8W, CUSTOMER_RFM_CLOTHING_REVN_RATE_16W, CUSTOMER_RFM_CLOTHING_REVN_RATE_32W, CUSTOMER_RFM_CLOTHING_REVN_RATE_52W,
        CUSTOMER_RFM_DELICATESSEN_REVN_RATE_1W, CUSTOMER_RFM_DELICATESSEN_REVN_RATE_2W, CUSTOMER_RFM_DELICATESSEN_REVN_RATE_4W, CUSTOMER_RFM_DELICATESSEN_REVN_RATE_8W, CUSTOMER_RFM_DELICATESSEN_REVN_RATE_16W, CUSTOMER_RFM_DELICATESSEN_REVN_RATE_32W, CUSTOMER_RFM_DELICATESSEN_REVN_RATE_52W,
        CUSTOMER_RFM_GARDEN_REVN_RATE_1W, CUSTOMER_RFM_GARDEN_REVN_RATE_2W, CUSTOMER_RFM_GARDEN_REVN_RATE_4W, CUSTOMER_RFM_GARDEN_REVN_RATE_8W, CUSTOMER_RFM_GARDEN_REVN_RATE_16W, CUSTOMER_RFM_GARDEN_REVN_RATE_32W, CUSTOMER_RFM_GARDEN_REVN_RATE_52W,
        CUSTOMER_RFM_HOME_REVN_RATE_1W, CUSTOMER_RFM_HOME_REVN_RATE_2W, CUSTOMER_RFM_HOME_REVN_RATE_4W, CUSTOMER_RFM_HOME_REVN_RATE_8W, CUSTOMER_RFM_HOME_REVN_RATE_16W, CUSTOMER_RFM_HOME_REVN_RATE_32W, CUSTOMER_RFM_HOME_REVN_RATE_52W,
        CUSTOMER_RFM_HOME_DECOR_REVN_RATE_1W, CUSTOMER_RFM_HOME_DECOR_REVN_RATE_2W, CUSTOMER_RFM_HOME_DECOR_REVN_RATE_4W, CUSTOMER_RFM_HOME_DECOR_REVN_RATE_8W, CUSTOMER_RFM_HOME_DECOR_REVN_RATE_16W, CUSTOMER_RFM_HOME_DECOR_REVN_RATE_32W, CUSTOMER_RFM_HOME_DECOR_REVN_RATE_52W,
        CUSTOMER_RFM_JEWELRY_REVN_RATE_1W, CUSTOMER_RFM_JEWELRY_REVN_RATE_2W, CUSTOMER_RFM_JEWELRY_REVN_RATE_4W, CUSTOMER_RFM_JEWELRY_REVN_RATE_8W, CUSTOMER_RFM_JEWELRY_REVN_RATE_16W, CUSTOMER_RFM_JEWELRY_REVN_RATE_32W, CUSTOMER_RFM_JEWELRY_REVN_RATE_52W,
        CUSTOMER_RFM_KITCHEN_REVN_RATE_1W, CUSTOMER_RFM_KITCHEN_REVN_RATE_2W, CUSTOMER_RFM_KITCHEN_REVN_RATE_4W, CUSTOMER_RFM_KITCHEN_REVN_RATE_8W, CUSTOMER_RFM_KITCHEN_REVN_RATE_16W, CUSTOMER_RFM_KITCHEN_REVN_RATE_32W, CUSTOMER_RFM_KITCHEN_REVN_RATE_52W,
        CUSTOMER_RFM_NOVELTY_REVN_RATE_1W, CUSTOMER_RFM_NOVELTY_REVN_RATE_2W, CUSTOMER_RFM_NOVELTY_REVN_RATE_4W, CUSTOMER_RFM_NOVELTY_REVN_RATE_8W, CUSTOMER_RFM_NOVELTY_REVN_RATE_16W, CUSTOMER_RFM_NOVELTY_REVN_RATE_32W, CUSTOMER_RFM_NOVELTY_REVN_RATE_52W,
        CUSTOMER_RFM_SCHOOL_SUPPLIES_REVN_RATE_1W, CUSTOMER_RFM_SCHOOL_SUPPLIES_REVN_RATE_2W, CUSTOMER_RFM_SCHOOL_SUPPLIES_REVN_RATE_4W, CUSTOMER_RFM_SCHOOL_SUPPLIES_REVN_RATE_8W, CUSTOMER_RFM_SCHOOL_SUPPLIES_REVN_RATE_16W, CUSTOMER_RFM_SCHOOL_SUPPLIES_REVN_RATE_32W, CUSTOMER_RFM_SCHOOL_SUPPLIES_REVN_RATE_52W,
        CUSTOMER_RFM_TOYS_REVN_RATE_1W, CUSTOMER_RFM_TOYS_REVN_RATE_2W, CUSTOMER_RFM_TOYS_REVN_RATE_4W, CUSTOMER_RFM_TOYS_REVN_RATE_8W, CUSTOMER_RFM_TOYS_REVN_RATE_16W, CUSTOMER_RFM_TOYS_REVN_RATE_32W, CUSTOMER_RFM_TOYS_REVN_RATE_52W,
        CUSTOMER_RFM_TRAVEL_REVN_RATE_1W, CUSTOMER_RFM_TRAVEL_REVN_RATE_2W, CUSTOMER_RFM_TRAVEL_REVN_RATE_4W, CUSTOMER_RFM_TRAVEL_REVN_RATE_8W, CUSTOMER_RFM_TRAVEL_REVN_RATE_16W, CUSTOMER_RFM_TRAVEL_REVN_RATE_32W, CUSTOMER_RFM_TRAVEL_REVN_RATE_52W,
        CUSTOMER_RFM_TOTAL_REVN_RATE_1W, CUSTOMER_RFM_TOTAL_REVN_RATE_2W, CUSTOMER_RFM_TOTAL_REVN_RATE_4W, CUSTOMER_RFM_TOTAL_REVN_RATE_8W, CUSTOMER_RFM_TOTAL_REVN_RATE_16W, CUSTOMER_RFM_TOTAL_REVN_RATE_32W, CUSTOMER_RFM_TOTAL_REVN_RATE_52W

)
 SELECT
            CUSTOMERID,
            ASOF_TS,
            current_timestamp as INGEST_TS,
            CUSTOMER_CLOTHING_RATE_1W, CUSTOMER_CLOTHING_RATE_2W, CUSTOMER_CLOTHING_RATE_4W, CUSTOMER_CLOTHING_RATE_8W, CUSTOMER_CLOTHING_RATE_16W, CUSTOMER_CLOTHING_RATE_32W, CUSTOMER_CLOTHING_RATE_52W,
            CUSTOMER_DELICATESSEN_RATE_1W, CUSTOMER_DELICATESSEN_RATE_2W, CUSTOMER_DELICATESSEN_RATE_4W, CUSTOMER_DELICATESSEN_RATE_8W, CUSTOMER_DELICATESSEN_RATE_16W, CUSTOMER_DELICATESSEN_RATE_32W, CUSTOMER_DELICATESSEN_RATE_52W,
            CUSTOMER_GARDEN_RATE_1W, CUSTOMER_GARDEN_RATE_2W, CUSTOMER_GARDEN_RATE_4W, CUSTOMER_GARDEN_RATE_8W, CUSTOMER_GARDEN_RATE_16W, CUSTOMER_GARDEN_RATE_32W, CUSTOMER_GARDEN_RATE_52W,
            CUSTOMER_HOME_RATE_1W, CUSTOMER_HOME_RATE_2W, CUSTOMER_HOME_RATE_4W, CUSTOMER_HOME_RATE_8W, CUSTOMER_HOME_RATE_16W, CUSTOMER_HOME_RATE_32W, CUSTOMER_HOME_RATE_52W,
            CUSTOMER_HOME_DECOR_RATE_1W, CUSTOMER_HOME_DECOR_RATE_2W, CUSTOMER_HOME_DECOR_RATE_4W, CUSTOMER_HOME_DECOR_RATE_8W, CUSTOMER_HOME_DECOR_RATE_16W, CUSTOMER_HOME_DECOR_RATE_32W, CUSTOMER_HOME_DECOR_RATE_52W,
            CUSTOMER_JEWELRY_RATE_1W, CUSTOMER_JEWELRY_RATE_2W, CUSTOMER_JEWELRY_RATE_4W, CUSTOMER_JEWELRY_RATE_8W, CUSTOMER_JEWELRY_RATE_16W, CUSTOMER_JEWELRY_RATE_32W, CUSTOMER_JEWELRY_RATE_52W,
            CUSTOMER_KITCHEN_RATE_1W, CUSTOMER_KITCHEN_RATE_2W, CUSTOMER_KITCHEN_RATE_4W, CUSTOMER_KITCHEN_RATE_8W, CUSTOMER_KITCHEN_RATE_16W, CUSTOMER_KITCHEN_RATE_32W, CUSTOMER_KITCHEN_RATE_52W,
            CUSTOMER_NOVELTY_RATE_1W, CUSTOMER_NOVELTY_RATE_2W, CUSTOMER_NOVELTY_RATE_4W, CUSTOMER_NOVELTY_RATE_8W, CUSTOMER_NOVELTY_RATE_16W, CUSTOMER_NOVELTY_RATE_32W, CUSTOMER_NOVELTY_RATE_52W,
            CUSTOMER_SCHOOL_SUPPLIES_RATE_1W, CUSTOMER_SCHOOL_SUPPLIES_RATE_2W, CUSTOMER_SCHOOL_SUPPLIES_RATE_4W, CUSTOMER_SCHOOL_SUPPLIES_RATE_8W, CUSTOMER_SCHOOL_SUPPLIES_RATE_16W, CUSTOMER_SCHOOL_SUPPLIES_RATE_32W, CUSTOMER_SCHOOL_SUPPLIES_RATE_52W,
            CUSTOMER_TOYS_RATE_1W, CUSTOMER_TOYS_RATE_2W, CUSTOMER_TOYS_RATE_4W, CUSTOMER_TOYS_RATE_8W, CUSTOMER_TOYS_RATE_16W, CUSTOMER_TOYS_RATE_32W, CUSTOMER_TOYS_RATE_52W,
            CUSTOMER_TRAVEL_RATE_1W, CUSTOMER_TRAVEL_RATE_2W, CUSTOMER_TRAVEL_RATE_4W, CUSTOMER_TRAVEL_RATE_8W, CUSTOMER_TRAVEL_RATE_16W, CUSTOMER_TRAVEL_RATE_32W, CUSTOMER_TRAVEL_RATE_52W,
            CUSTOMER_TOTAL_RATE_1W, CUSTOMER_TOTAL_RATE_2W, CUSTOMER_TOTAL_RATE_4W, CUSTOMER_TOTAL_RATE_8W, CUSTOMER_TOTAL_RATE_16W, CUSTOMER_TOTAL_RATE_32W, CUSTOMER_TOTAL_RATE_52W,

            CUSTOMER_CLOTHING_REVN_RATE_1W, CUSTOMER_CLOTHING_REVN_RATE_2W, CUSTOMER_CLOTHING_REVN_RATE_4W, CUSTOMER_CLOTHING_REVN_RATE_8W, CUSTOMER_CLOTHING_REVN_RATE_16W, CUSTOMER_CLOTHING_REVN_RATE_32W, CUSTOMER_CLOTHING_REVN_RATE_52W,
            CUSTOMER_DELICATESSEN_REVN_RATE_1W, CUSTOMER_DELICATESSEN_REVN_RATE_2W, CUSTOMER_DELICATESSEN_REVN_RATE_4W, CUSTOMER_DELICATESSEN_REVN_RATE_8W, CUSTOMER_DELICATESSEN_REVN_RATE_16W, CUSTOMER_DELICATESSEN_REVN_RATE_32W, CUSTOMER_DELICATESSEN_REVN_RATE_52W,
            CUSTOMER_GARDEN_REVN_RATE_1W, CUSTOMER_GARDEN_REVN_RATE_2W, CUSTOMER_GARDEN_REVN_RATE_4W, CUSTOMER_GARDEN_REVN_RATE_8W, CUSTOMER_GARDEN_REVN_RATE_16W, CUSTOMER_GARDEN_REVN_RATE_32W, CUSTOMER_GARDEN_REVN_RATE_52W,
            CUSTOMER_HOME_REVN_RATE_1W, CUSTOMER_HOME_REVN_RATE_2W, CUSTOMER_HOME_REVN_RATE_4W, CUSTOMER_HOME_REVN_RATE_8W, CUSTOMER_HOME_REVN_RATE_16W, CUSTOMER_HOME_REVN_RATE_32W, CUSTOMER_HOME_REVN_RATE_52W,
            CUSTOMER_HOME_DECOR_REVN_RATE_1W, CUSTOMER_HOME_DECOR_REVN_RATE_2W, CUSTOMER_HOME_DECOR_REVN_RATE_4W, CUSTOMER_HOME_DECOR_REVN_RATE_8W, CUSTOMER_HOME_DECOR_REVN_RATE_16W, CUSTOMER_HOME_DECOR_REVN_RATE_32W, CUSTOMER_HOME_DECOR_REVN_RATE_52W,
            CUSTOMER_JEWELRY_REVN_RATE_1W, CUSTOMER_JEWELRY_REVN_RATE_2W, CUSTOMER_JEWELRY_REVN_RATE_4W, CUSTOMER_JEWELRY_REVN_RATE_8W, CUSTOMER_JEWELRY_REVN_RATE_16W, CUSTOMER_JEWELRY_REVN_RATE_32W, CUSTOMER_JEWELRY_REVN_RATE_52W,
            CUSTOMER_KITCHEN_REVN_RATE_1W, CUSTOMER_KITCHEN_REVN_RATE_2W, CUSTOMER_KITCHEN_REVN_RATE_4W, CUSTOMER_KITCHEN_REVN_RATE_8W, CUSTOMER_KITCHEN_REVN_RATE_16W, CUSTOMER_KITCHEN_REVN_RATE_32W, CUSTOMER_KITCHEN_REVN_RATE_52W,
            CUSTOMER_NOVELTY_REVN_RATE_1W, CUSTOMER_NOVELTY_REVN_RATE_2W, CUSTOMER_NOVELTY_REVN_RATE_4W, CUSTOMER_NOVELTY_REVN_RATE_8W, CUSTOMER_NOVELTY_REVN_RATE_16W, CUSTOMER_NOVELTY_REVN_RATE_32W, CUSTOMER_NOVELTY_REVN_RATE_52W,
            CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_1W, CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_2W, CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_4W, CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_8W, CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_16W, CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_32W, CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_52W,
            CUSTOMER_TOYS_REVN_RATE_1W, CUSTOMER_TOYS_REVN_RATE_2W, CUSTOMER_TOYS_REVN_RATE_4W, CUSTOMER_TOYS_REVN_RATE_8W, CUSTOMER_TOYS_REVN_RATE_16W, CUSTOMER_TOYS_REVN_RATE_32W, CUSTOMER_TOYS_REVN_RATE_52W,
            CUSTOMER_TRAVEL_REVN_RATE_1W, CUSTOMER_TRAVEL_REVN_RATE_2W, CUSTOMER_TRAVEL_REVN_RATE_4W, CUSTOMER_TRAVEL_REVN_RATE_8W, CUSTOMER_TRAVEL_REVN_RATE_16W, CUSTOMER_TRAVEL_REVN_RATE_32W, CUSTOMER_TRAVEL_REVN_RATE_52W,
            CUSTOMER_TOTAL_REVN_RATE_1W, CUSTOMER_TOTAL_REVN_RATE_2W, CUSTOMER_TOTAL_REVN_RATE_4W, CUSTOMER_TOTAL_REVN_RATE_8W, CUSTOMER_TOTAL_REVN_RATE_16W, CUSTOMER_TOTAL_REVN_RATE_32W, CUSTOMER_TOTAL_REVN_RATE_52W
FROM
(

SELECT * FROM
    (
        SELECT
            CUSTOMERID,
            LAST_UPDATE_TS AS ASOF_TS,
            LAST_VALUE(LAST_UPDATE_TS) OVER (PARTITION BY CUSTOMERID ORDER BY LAST_UPDATE_TS ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) UNTIL_TS,
            CUSTOMER_CLOTHING_RATE_1W, CUSTOMER_CLOTHING_RATE_2W, CUSTOMER_CLOTHING_RATE_4W, CUSTOMER_CLOTHING_RATE_8W, CUSTOMER_CLOTHING_RATE_16W, CUSTOMER_CLOTHING_RATE_32W, CUSTOMER_CLOTHING_RATE_52W,
            CUSTOMER_DELICATESSEN_RATE_1W, CUSTOMER_DELICATESSEN_RATE_2W, CUSTOMER_DELICATESSEN_RATE_4W, CUSTOMER_DELICATESSEN_RATE_8W, CUSTOMER_DELICATESSEN_RATE_16W, CUSTOMER_DELICATESSEN_RATE_32W, CUSTOMER_DELICATESSEN_RATE_52W,
            CUSTOMER_GARDEN_RATE_1W, CUSTOMER_GARDEN_RATE_2W, CUSTOMER_GARDEN_RATE_4W, CUSTOMER_GARDEN_RATE_8W, CUSTOMER_GARDEN_RATE_16W, CUSTOMER_GARDEN_RATE_32W, CUSTOMER_GARDEN_RATE_52W,
            CUSTOMER_HOME_RATE_1W, CUSTOMER_HOME_RATE_2W, CUSTOMER_HOME_RATE_4W, CUSTOMER_HOME_RATE_8W, CUSTOMER_HOME_RATE_16W, CUSTOMER_HOME_RATE_32W, CUSTOMER_HOME_RATE_52W,
            CUSTOMER_HOME_DECOR_RATE_1W, CUSTOMER_HOME_DECOR_RATE_2W, CUSTOMER_HOME_DECOR_RATE_4W, CUSTOMER_HOME_DECOR_RATE_8W, CUSTOMER_HOME_DECOR_RATE_16W, CUSTOMER_HOME_DECOR_RATE_32W, CUSTOMER_HOME_DECOR_RATE_52W,
            CUSTOMER_JEWELRY_RATE_1W, CUSTOMER_JEWELRY_RATE_2W, CUSTOMER_JEWELRY_RATE_4W, CUSTOMER_JEWELRY_RATE_8W, CUSTOMER_JEWELRY_RATE_16W, CUSTOMER_JEWELRY_RATE_32W, CUSTOMER_JEWELRY_RATE_52W,
            CUSTOMER_KITCHEN_RATE_1W, CUSTOMER_KITCHEN_RATE_2W, CUSTOMER_KITCHEN_RATE_4W, CUSTOMER_KITCHEN_RATE_8W, CUSTOMER_KITCHEN_RATE_16W, CUSTOMER_KITCHEN_RATE_32W, CUSTOMER_KITCHEN_RATE_52W,
            CUSTOMER_NOVELTY_RATE_1W, CUSTOMER_NOVELTY_RATE_2W, CUSTOMER_NOVELTY_RATE_4W, CUSTOMER_NOVELTY_RATE_8W, CUSTOMER_NOVELTY_RATE_16W, CUSTOMER_NOVELTY_RATE_32W, CUSTOMER_NOVELTY_RATE_52W,
            CUSTOMER_SCHOOL_SUPPLIES_RATE_1W, CUSTOMER_SCHOOL_SUPPLIES_RATE_2W, CUSTOMER_SCHOOL_SUPPLIES_RATE_4W, CUSTOMER_SCHOOL_SUPPLIES_RATE_8W, CUSTOMER_SCHOOL_SUPPLIES_RATE_16W, CUSTOMER_SCHOOL_SUPPLIES_RATE_32W, CUSTOMER_SCHOOL_SUPPLIES_RATE_52W,
            CUSTOMER_TOYS_RATE_1W, CUSTOMER_TOYS_RATE_2W, CUSTOMER_TOYS_RATE_4W, CUSTOMER_TOYS_RATE_8W, CUSTOMER_TOYS_RATE_16W, CUSTOMER_TOYS_RATE_32W, CUSTOMER_TOYS_RATE_52W,
            CUSTOMER_TRAVEL_RATE_1W, CUSTOMER_TRAVEL_RATE_2W, CUSTOMER_TRAVEL_RATE_4W, CUSTOMER_TRAVEL_RATE_8W, CUSTOMER_TRAVEL_RATE_16W, CUSTOMER_TRAVEL_RATE_32W, CUSTOMER_TRAVEL_RATE_52W,
            CUSTOMER_TOTAL_RATE_1W, CUSTOMER_TOTAL_RATE_2W, CUSTOMER_TOTAL_RATE_4W, CUSTOMER_TOTAL_RATE_8W, CUSTOMER_TOTAL_RATE_16W, CUSTOMER_TOTAL_RATE_32W, CUSTOMER_TOTAL_RATE_52W,

            CUSTOMER_CLOTHING_REVN_RATE_1W, CUSTOMER_CLOTHING_REVN_RATE_2W, CUSTOMER_CLOTHING_REVN_RATE_4W, CUSTOMER_CLOTHING_REVN_RATE_8W, CUSTOMER_CLOTHING_REVN_RATE_16W, CUSTOMER_CLOTHING_REVN_RATE_32W, CUSTOMER_CLOTHING_REVN_RATE_52W,
            CUSTOMER_DELICATESSEN_REVN_RATE_1W, CUSTOMER_DELICATESSEN_REVN_RATE_2W, CUSTOMER_DELICATESSEN_REVN_RATE_4W, CUSTOMER_DELICATESSEN_REVN_RATE_8W, CUSTOMER_DELICATESSEN_REVN_RATE_16W, CUSTOMER_DELICATESSEN_REVN_RATE_32W, CUSTOMER_DELICATESSEN_REVN_RATE_52W,
            CUSTOMER_GARDEN_REVN_RATE_1W, CUSTOMER_GARDEN_REVN_RATE_2W, CUSTOMER_GARDEN_REVN_RATE_4W, CUSTOMER_GARDEN_REVN_RATE_8W, CUSTOMER_GARDEN_REVN_RATE_16W, CUSTOMER_GARDEN_REVN_RATE_32W, CUSTOMER_GARDEN_REVN_RATE_52W,
            CUSTOMER_HOME_REVN_RATE_1W, CUSTOMER_HOME_REVN_RATE_2W, CUSTOMER_HOME_REVN_RATE_4W, CUSTOMER_HOME_REVN_RATE_8W, CUSTOMER_HOME_REVN_RATE_16W, CUSTOMER_HOME_REVN_RATE_32W, CUSTOMER_HOME_REVN_RATE_52W,
            CUSTOMER_HOME_DECOR_REVN_RATE_1W, CUSTOMER_HOME_DECOR_REVN_RATE_2W, CUSTOMER_HOME_DECOR_REVN_RATE_4W, CUSTOMER_HOME_DECOR_REVN_RATE_8W, CUSTOMER_HOME_DECOR_REVN_RATE_16W, CUSTOMER_HOME_DECOR_REVN_RATE_32W, CUSTOMER_HOME_DECOR_REVN_RATE_52W,
            CUSTOMER_JEWELRY_REVN_RATE_1W, CUSTOMER_JEWELRY_REVN_RATE_2W, CUSTOMER_JEWELRY_REVN_RATE_4W, CUSTOMER_JEWELRY_REVN_RATE_8W, CUSTOMER_JEWELRY_REVN_RATE_16W, CUSTOMER_JEWELRY_REVN_RATE_32W, CUSTOMER_JEWELRY_REVN_RATE_52W,
            CUSTOMER_KITCHEN_REVN_RATE_1W, CUSTOMER_KITCHEN_REVN_RATE_2W, CUSTOMER_KITCHEN_REVN_RATE_4W, CUSTOMER_KITCHEN_REVN_RATE_8W, CUSTOMER_KITCHEN_REVN_RATE_16W, CUSTOMER_KITCHEN_REVN_RATE_32W, CUSTOMER_KITCHEN_REVN_RATE_52W,
            CUSTOMER_NOVELTY_REVN_RATE_1W, CUSTOMER_NOVELTY_REVN_RATE_2W, CUSTOMER_NOVELTY_REVN_RATE_4W, CUSTOMER_NOVELTY_REVN_RATE_8W, CUSTOMER_NOVELTY_REVN_RATE_16W, CUSTOMER_NOVELTY_REVN_RATE_32W, CUSTOMER_NOVELTY_REVN_RATE_52W,
            CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_1W, CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_2W, CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_4W, CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_8W, CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_16W, CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_32W, CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_52W,
            CUSTOMER_TOYS_REVN_RATE_1W, CUSTOMER_TOYS_REVN_RATE_2W, CUSTOMER_TOYS_REVN_RATE_4W, CUSTOMER_TOYS_REVN_RATE_8W, CUSTOMER_TOYS_REVN_RATE_16W, CUSTOMER_TOYS_REVN_RATE_32W, CUSTOMER_TOYS_REVN_RATE_52W,
            CUSTOMER_TRAVEL_REVN_RATE_1W, CUSTOMER_TRAVEL_REVN_RATE_2W, CUSTOMER_TRAVEL_REVN_RATE_4W, CUSTOMER_TRAVEL_REVN_RATE_8W, CUSTOMER_TRAVEL_REVN_RATE_16W, CUSTOMER_TRAVEL_REVN_RATE_32W, CUSTOMER_TRAVEL_REVN_RATE_52W,
            CUSTOMER_TOTAL_REVN_RATE_1W, CUSTOMER_TOTAL_REVN_RATE_2W, CUSTOMER_TOTAL_REVN_RATE_4W, CUSTOMER_TOTAL_REVN_RATE_8W, CUSTOMER_TOTAL_REVN_RATE_16W, CUSTOMER_TOTAL_REVN_RATE_32W, CUSTOMER_TOTAL_REVN_RATE_52W

        FROM
        (
            SELECT
                CUSTOMERID, CAST(w.week_end_date AS TIMESTAMP) AS LAST_UPDATE_TS,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   CLOTHING_QTY END),0.0)      CUSTOMER_CLOTHING_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  CLOTHING_QTY END)/2.0,0.0)  CUSTOMER_CLOTHING_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  CLOTHING_QTY END)/4.0,0.0)  CUSTOMER_CLOTHING_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  CLOTHING_QTY END)/8.0,0.0)  CUSTOMER_CLOTHING_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN CLOTHING_QTY END)/16.0,0.0) CUSTOMER_CLOTHING_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN CLOTHING_QTY END)/32.0,0.0) CUSTOMER_CLOTHING_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN CLOTHING_QTY END)/52.0,0.0) CUSTOMER_CLOTHING_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   DELICATESSEN_QTY END),0.0)      CUSTOMER_DELICATESSEN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  DELICATESSEN_QTY END)/2.0,0.0)  CUSTOMER_DELICATESSEN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  DELICATESSEN_QTY END)/4.0,0.0)  CUSTOMER_DELICATESSEN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  DELICATESSEN_QTY END)/8.0,0.0)  CUSTOMER_DELICATESSEN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN DELICATESSEN_QTY END)/16.0,0.0) CUSTOMER_DELICATESSEN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN DELICATESSEN_QTY END)/32.0,0.0) CUSTOMER_DELICATESSEN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN DELICATESSEN_QTY END)/52.0,0.0) CUSTOMER_DELICATESSEN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   GARDEN_QTY END),0.0)      CUSTOMER_GARDEN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  GARDEN_QTY END)/2.0,0.0)  CUSTOMER_GARDEN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  GARDEN_QTY END)/4.0,0.0)  CUSTOMER_GARDEN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  GARDEN_QTY END)/8.0,0.0)  CUSTOMER_GARDEN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN GARDEN_QTY END)/16.0,0.0) CUSTOMER_GARDEN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN GARDEN_QTY END)/32.0,0.0) CUSTOMER_GARDEN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN GARDEN_QTY END)/52.0,0.0) CUSTOMER_GARDEN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   HOME_QTY END),0.0)      CUSTOMER_HOME_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  HOME_QTY END)/2.0,0.0)  CUSTOMER_HOME_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  HOME_QTY END)/4.0,0.0)  CUSTOMER_HOME_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  HOME_QTY END)/8.0,0.0)  CUSTOMER_HOME_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN HOME_QTY END)/16.0,0.0) CUSTOMER_HOME_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN HOME_QTY END)/32.0,0.0) CUSTOMER_HOME_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN HOME_QTY END)/52.0,0.0) CUSTOMER_HOME_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   HOME_DECOR_QTY END),0.0)      CUSTOMER_HOME_DECOR_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  HOME_DECOR_QTY END)/2.0,0.0)  CUSTOMER_HOME_DECOR_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  HOME_DECOR_QTY END)/4.0,0.0)  CUSTOMER_HOME_DECOR_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  HOME_DECOR_QTY END)/8.0,0.0)  CUSTOMER_HOME_DECOR_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN HOME_DECOR_QTY END)/16.0,0.0) CUSTOMER_HOME_DECOR_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN HOME_DECOR_QTY END)/32.0,0.0) CUSTOMER_HOME_DECOR_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN HOME_DECOR_QTY END)/52.0,0.0) CUSTOMER_HOME_DECOR_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   JEWELRY_QTY END),0.0)      CUSTOMER_JEWELRY_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  JEWELRY_QTY END)/2.0,0.0)  CUSTOMER_JEWELRY_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  JEWELRY_QTY END)/4.0,0.0)  CUSTOMER_JEWELRY_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  JEWELRY_QTY END)/8.0,0.0)  CUSTOMER_JEWELRY_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN JEWELRY_QTY END)/16.0,0.0) CUSTOMER_JEWELRY_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN JEWELRY_QTY END)/32.0,0.0) CUSTOMER_JEWELRY_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN JEWELRY_QTY END)/52.0,0.0) CUSTOMER_JEWELRY_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   KITCHEN_QTY END),0.0)      CUSTOMER_KITCHEN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  KITCHEN_QTY END)/2.0,0.0)  CUSTOMER_KITCHEN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  KITCHEN_QTY END)/4.0,0.0)  CUSTOMER_KITCHEN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  KITCHEN_QTY END)/8.0,0.0)  CUSTOMER_KITCHEN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN KITCHEN_QTY END)/16.0,0.0) CUSTOMER_KITCHEN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN KITCHEN_QTY END)/32.0,0.0) CUSTOMER_KITCHEN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN KITCHEN_QTY END)/52.0,0.0) CUSTOMER_KITCHEN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   NOVELTY_QTY END),0.0)      CUSTOMER_NOVELTY_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  NOVELTY_QTY END)/2.0,0.0)  CUSTOMER_NOVELTY_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  NOVELTY_QTY END)/4.0,0.0)  CUSTOMER_NOVELTY_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  NOVELTY_QTY END)/8.0,0.0)  CUSTOMER_NOVELTY_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN NOVELTY_QTY END)/16.0,0.0) CUSTOMER_NOVELTY_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN NOVELTY_QTY END)/32.0,0.0) CUSTOMER_NOVELTY_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN NOVELTY_QTY END)/52.0,0.0) CUSTOMER_NOVELTY_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   SCHOOL_SUPPLIES_QTY END),0.0)      CUSTOMER_SCHOOL_SUPPLIES_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  SCHOOL_SUPPLIES_QTY END)/2.0,0.0)  CUSTOMER_SCHOOL_SUPPLIES_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  SCHOOL_SUPPLIES_QTY END)/4.0,0.0)  CUSTOMER_SCHOOL_SUPPLIES_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  SCHOOL_SUPPLIES_QTY END)/8.0,0.0)  CUSTOMER_SCHOOL_SUPPLIES_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN SCHOOL_SUPPLIES_QTY END)/16.0,0.0) CUSTOMER_SCHOOL_SUPPLIES_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN SCHOOL_SUPPLIES_QTY END)/32.0,0.0) CUSTOMER_SCHOOL_SUPPLIES_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN SCHOOL_SUPPLIES_QTY END)/52.0,0.0) CUSTOMER_SCHOOL_SUPPLIES_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   TOYS_QTY END),0.0)      CUSTOMER_TOYS_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  TOYS_QTY END)/2.0,0.0)  CUSTOMER_TOYS_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  TOYS_QTY END)/4.0,0.0)  CUSTOMER_TOYS_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  TOYS_QTY END)/8.0,0.0)  CUSTOMER_TOYS_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN TOYS_QTY END)/16.0,0.0) CUSTOMER_TOYS_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN TOYS_QTY END)/32.0,0.0) CUSTOMER_TOYS_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN TOYS_QTY END)/52.0,0.0) CUSTOMER_TOYS_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   TRAVEL_QTY END),0.0)      CUSTOMER_TRAVEL_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  TRAVEL_QTY END)/2.0,0.0)  CUSTOMER_TRAVEL_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  TRAVEL_QTY END)/4.0,0.0)  CUSTOMER_TRAVEL_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  TRAVEL_QTY END)/8.0,0.0)  CUSTOMER_TRAVEL_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN TRAVEL_QTY END)/16.0,0.0) CUSTOMER_TRAVEL_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN TRAVEL_QTY END)/32.0,0.0) CUSTOMER_TRAVEL_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN TRAVEL_QTY END)/52.0,0.0) CUSTOMER_TRAVEL_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   TOTAL_QTY END),0.0)      CUSTOMER_TOTAL_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  TOTAL_QTY END)/2.0,0.0)  CUSTOMER_TOTAL_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  TOTAL_QTY END)/4.0,0.0)  CUSTOMER_TOTAL_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  TOTAL_QTY END)/8.0,0.0)  CUSTOMER_TOTAL_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN TOTAL_QTY END)/16.0,0.0) CUSTOMER_TOTAL_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN TOTAL_QTY END)/32.0,0.0) CUSTOMER_TOTAL_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN TOTAL_QTY END)/52.0,0.0) CUSTOMER_TOTAL_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   CLOTHING_REVENUE END),0.0)      CUSTOMER_CLOTHING_REVN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  CLOTHING_REVENUE END)/2.0,0.0)  CUSTOMER_CLOTHING_REVN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  CLOTHING_REVENUE END)/4.0,0.0)  CUSTOMER_CLOTHING_REVN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  CLOTHING_REVENUE END)/8.0,0.0)  CUSTOMER_CLOTHING_REVN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN CLOTHING_REVENUE END)/16.0,0.0) CUSTOMER_CLOTHING_REVN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN CLOTHING_REVENUE END)/32.0,0.0) CUSTOMER_CLOTHING_REVN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN CLOTHING_REVENUE END)/52.0,0.0) CUSTOMER_CLOTHING_REVN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   DELICATESSEN_REVENUE END),0.0)      CUSTOMER_DELICATESSEN_REVN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  DELICATESSEN_REVENUE END)/2.0,0.0)  CUSTOMER_DELICATESSEN_REVN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  DELICATESSEN_REVENUE END)/4.0,0.0)  CUSTOMER_DELICATESSEN_REVN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  DELICATESSEN_REVENUE END)/8.0,0.0)  CUSTOMER_DELICATESSEN_REVN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN DELICATESSEN_REVENUE END)/16.0,0.0) CUSTOMER_DELICATESSEN_REVN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN DELICATESSEN_REVENUE END)/32.0,0.0) CUSTOMER_DELICATESSEN_REVN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN DELICATESSEN_REVENUE END)/52.0,0.0) CUSTOMER_DELICATESSEN_REVN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   GARDEN_REVENUE END),0.0)      CUSTOMER_GARDEN_REVN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  GARDEN_REVENUE END)/2.0,0.0)  CUSTOMER_GARDEN_REVN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  GARDEN_REVENUE END)/4.0,0.0)  CUSTOMER_GARDEN_REVN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  GARDEN_REVENUE END)/8.0,0.0)  CUSTOMER_GARDEN_REVN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN GARDEN_REVENUE END)/16.0,0.0) CUSTOMER_GARDEN_REVN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN GARDEN_REVENUE END)/32.0,0.0) CUSTOMER_GARDEN_REVN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN GARDEN_REVENUE END)/52.0,0.0) CUSTOMER_GARDEN_REVN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   HOME_REVENUE END),0.0)      CUSTOMER_HOME_REVN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  HOME_REVENUE END)/2.0,0.0)  CUSTOMER_HOME_REVN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  HOME_REVENUE END)/4.0,0.0)  CUSTOMER_HOME_REVN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  HOME_REVENUE END)/8.0,0.0)  CUSTOMER_HOME_REVN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN HOME_REVENUE END)/16.0,0.0) CUSTOMER_HOME_REVN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN HOME_REVENUE END)/32.0,0.0) CUSTOMER_HOME_REVN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN HOME_REVENUE END)/52.0,0.0) CUSTOMER_HOME_REVN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   HOME_DECOR_REVENUE END),0.0)      CUSTOMER_HOME_DECOR_REVN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  HOME_DECOR_REVENUE END)/2.0,0.0)  CUSTOMER_HOME_DECOR_REVN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  HOME_DECOR_REVENUE END)/4.0,0.0)  CUSTOMER_HOME_DECOR_REVN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  HOME_DECOR_REVENUE END)/8.0,0.0)  CUSTOMER_HOME_DECOR_REVN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN HOME_DECOR_REVENUE END)/16.0,0.0) CUSTOMER_HOME_DECOR_REVN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN HOME_DECOR_REVENUE END)/32.0,0.0) CUSTOMER_HOME_DECOR_REVN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN HOME_DECOR_REVENUE END)/52.0,0.0) CUSTOMER_HOME_DECOR_REVN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   JEWELRY_REVENUE END),0.0)      CUSTOMER_JEWELRY_REVN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  JEWELRY_REVENUE END)/2.0,0.0)  CUSTOMER_JEWELRY_REVN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  JEWELRY_REVENUE END)/4.0,0.0)  CUSTOMER_JEWELRY_REVN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  JEWELRY_REVENUE END)/8.0,0.0)  CUSTOMER_JEWELRY_REVN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN JEWELRY_REVENUE END)/16.0,0.0) CUSTOMER_JEWELRY_REVN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN JEWELRY_REVENUE END)/32.0,0.0) CUSTOMER_JEWELRY_REVN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN JEWELRY_REVENUE END)/52.0,0.0) CUSTOMER_JEWELRY_REVN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   KITCHEN_REVENUE END),0.0)      CUSTOMER_KITCHEN_REVN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  KITCHEN_REVENUE END)/2.0,0.0)  CUSTOMER_KITCHEN_REVN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  KITCHEN_REVENUE END)/4.0,0.0)  CUSTOMER_KITCHEN_REVN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  KITCHEN_REVENUE END)/8.0,0.0)  CUSTOMER_KITCHEN_REVN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN KITCHEN_REVENUE END)/16.0,0.0) CUSTOMER_KITCHEN_REVN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN KITCHEN_REVENUE END)/32.0,0.0) CUSTOMER_KITCHEN_REVN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN KITCHEN_REVENUE END)/52.0,0.0) CUSTOMER_KITCHEN_REVN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   NOVELTY_REVENUE END),0.0)      CUSTOMER_NOVELTY_REVN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  NOVELTY_REVENUE END)/2.0,0.0)  CUSTOMER_NOVELTY_REVN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  NOVELTY_REVENUE END)/4.0,0.0)  CUSTOMER_NOVELTY_REVN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  NOVELTY_REVENUE END)/8.0,0.0)  CUSTOMER_NOVELTY_REVN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN NOVELTY_REVENUE END)/16.0,0.0) CUSTOMER_NOVELTY_REVN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN NOVELTY_REVENUE END)/32.0,0.0) CUSTOMER_NOVELTY_REVN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN NOVELTY_REVENUE END)/52.0,0.0) CUSTOMER_NOVELTY_REVN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   SCHOOL_SUPPLIES_REVENUE END),0.0)      CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  SCHOOL_SUPPLIES_REVENUE END)/2.0,0.0)  CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  SCHOOL_SUPPLIES_REVENUE END)/4.0,0.0)  CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  SCHOOL_SUPPLIES_REVENUE END)/8.0,0.0)  CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN SCHOOL_SUPPLIES_REVENUE END)/16.0,0.0) CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN SCHOOL_SUPPLIES_REVENUE END)/32.0,0.0) CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN SCHOOL_SUPPLIES_REVENUE END)/52.0,0.0) CUSTOMER_SCHOOL_SUPPLIES_REVN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   TOYS_REVENUE END),0.0)      CUSTOMER_TOYS_REVN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  TOYS_REVENUE END)/2.0,0.0)  CUSTOMER_TOYS_REVN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  TOYS_REVENUE END)/4.0,0.0)  CUSTOMER_TOYS_REVN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  TOYS_REVENUE END)/8.0,0.0)  CUSTOMER_TOYS_REVN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN TOYS_REVENUE END)/16.0,0.0) CUSTOMER_TOYS_REVN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN TOYS_REVENUE END)/32.0,0.0) CUSTOMER_TOYS_REVN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN TOYS_REVENUE END)/52.0,0.0) CUSTOMER_TOYS_REVN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   TRAVEL_REVENUE END),0.0)      CUSTOMER_TRAVEL_REVN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  TRAVEL_REVENUE END)/2.0,0.0)  CUSTOMER_TRAVEL_REVN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  TRAVEL_REVENUE END)/4.0,0.0)  CUSTOMER_TRAVEL_REVN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  TRAVEL_REVENUE END)/8.0,0.0)  CUSTOMER_TRAVEL_REVN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN TRAVEL_REVENUE END)/16.0,0.0) CUSTOMER_TRAVEL_REVN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN TRAVEL_REVENUE END)/32.0,0.0) CUSTOMER_TRAVEL_REVN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN TRAVEL_REVENUE END)/52.0,0.0) CUSTOMER_TRAVEL_REVN_RATE_52W,

                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 7 THEN   TOTAL_REVENUE END),0.0)      CUSTOMER_TOTAL_REVN_RATE_1W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 14 THEN  TOTAL_REVENUE END)/2.0,0.0)  CUSTOMER_TOTAL_REVN_RATE_2W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 28 THEN  TOTAL_REVENUE END)/4.0,0.0)  CUSTOMER_TOTAL_REVN_RATE_4W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 56 THEN  TOTAL_REVENUE END)/8.0,0.0)  CUSTOMER_TOTAL_REVN_RATE_8W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 112 THEN TOTAL_REVENUE END)/16.0,0.0) CUSTOMER_TOTAL_REVN_RATE_16W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 224 THEN TOTAL_REVENUE END)/32.0,0.0) CUSTOMER_TOTAL_REVN_RATE_32W,
                COALESCE(SUM(CASE WHEN w.week_end_date - INVOICEDATE BETWEEN 1 AND 364 THEN TOTAL_REVENUE END)/52.0,0.0) CUSTOMER_TOTAL_REVN_RATE_52W

            FROM RETAIL_RFM.CUSTOMER_CATEGORY_ACTIVITY cca --splice-properties splits=52
            INNER JOIN RETAIL_RFM.WEEKS w
               ON cca.INVOICEDATE BETWEEN w.week_end_date-364 AND w.week_end_date - 1   -- a whole year ending on the week_end_date for each week period
     --             AND w.week_end_date > current_date - 365 -- calculate each week for 1 year, once a week
            WHERE CUSTOMERID IS NOT NULL
            GROUP BY 1,2
        )x
    )y
    WHERE UNTIL_TS IS NOT NULL
);

