alter table mlmanager.models add column LIBRARY varchar(32) not null default 'mleap';
alter table mlmanager.models add column "version" varchar(32) not null default '0.15.0';
update mlmanager.artifacts set file_extension='spark' where file_extension='sparkmodel';

drop function MLMANAGER.PREDICT_CLASSIFICATION;
drop function MLMANAGER.PREDICT_REGRESSION;
drop function MLMANAGER.PREDICT_CLUSTER;
drop function MLMANAGER.PREDICT_CLUSTER_PROBABILITIES;
drop function MLMANAGER.PARSEPROBS;
drop function MLMANAGER.GETPREDICTION;

CREATE FUNCTION MLMANAGER.PREDICT_CLASSIFICATION(MODEL_PATH VARCHAR(256),MODEL_PARAMS VARCHAR(5000), MODEL_SCHEMA VARCHAR(7000))
RETURNS VARCHAR(1000) PARAMETER STYLE JAVA
LANGUAGE JAVA
EXTERNAL NAME 'com.splicemachine.mlrunner.MLRunner.predictClassification';
GRANT EXECUTE ON FUNCTION MLMANAGER.PREDICT_CLASSIFICATION TO PUBLIC;

CREATE FUNCTION MLMANAGER.PREDICT_REGRESSION(MODEL_PATH VARCHAR(256),MODEL_PARAMS VARCHAR(5000), MODEL_SCHEMA VARCHAR(7000))
RETURNS DOUBLE PARAMETER STYLE JAVA
LANGUAGE JAVA
EXTERNAL NAME 'com.splicemachine.mlrunner.MLRunner.predictRegression';
GRANT EXECUTE ON FUNCTION MLMANAGER.PREDICT_REGRESSION TO PUBLIC;

CREATE FUNCTION MLMANAGER.PREDICT_CLUSTER(MODEL_PATH VARCHAR(256),MODEL_PARAMS VARCHAR(5000), MODEL_SCHEMA VARCHAR(7000))
RETURNS INT PARAMETER STYLE JAVA
LANGUAGE JAVA
EXTERNAL NAME 'com.splicemachine.mlrunner.MLRunner.predictCluster';
GRANT EXECUTE ON FUNCTION MLMANAGER.PREDICT_CLUSTER TO PUBLIC;

CREATE FUNCTION MLMANAGER.PREDICT_CLUSTER_PROBABILITIES(MODEL_PATH VARCHAR(256),MODEL_PARAMS VARCHAR(5000), MODEL_SCHEMA VARCHAR(7000)
) RETURNS VARCHAR(1000) PARAMETER STYLE JAVA
LANGUAGE JAVA
EXTERNAL NAME 'com.splicemachine.mlrunner.MLRunner.predictClusterProbabilities';
GRANT EXECUTE ON FUNCTION MLMANAGER.PREDICT_CLUSTER_PROBABILITIES TO PUBLIC;

CREATE FUNCTION MLMANAGER.PARSEPROBS(MODELRESULT VARCHAR(1000), INDEX INTEGER)
RETURNS FLOAT PARAMETER STYLE JAVA
NO SQL LANGUAGE JAVA
EXTERNAL NAME 'com.splicemachine.mlrunner.MLRunner.splitResult';
GRANT EXECUTE ON FUNCTION MLMANAGER.PARSEPROBS TO PUBLIC;

CREATE FUNCTION MLMANAGER.GETPREDICTION(res VARCHAR(1000))
RETURNS INT PARAMETER STYLE JAVA
NO SQL LANGUAGE JAVA
EXTERNAL NAME 'com.splicemachine.mlrunner.MLRunner.getPrediction';
GRANT EXECUTE ON FUNCTION MLMANAGER.GETPREDICTION TO PUBLIC;
