ALTER TABLE MLMANAGER.ARTIFACTS ADD COLUMN DATABASE_BINARY BLOB(2G);
UPDATE MLMANAGER.ARTIFACTS SET DATABASE_BINARY=
SELECT a.MODEL FROM MLMANAGER.MODELS a join MLMANAGER.TAGS t on a.run_uuid=t.run_uuid and a.name=t."value"
where t."key"='splice.model_name'; 
