apiVersion: v1
kind: Service
metadata:
  name: model-{{ .Values.model.runId }}
  namespace: {{ .Values.model.namespace }}
  labels:
    identifier: model-{{ .Values.model.runId }}
  ownerReferences:
    - apiVersion: v1
      controller: true
      kind: Pod
      name: {{ .Values.k8s.ownerPod }}
      uid: {{ .Values.k8s.ownerUID }}
spec:
  clusterIP: None
  selector:
    identifier: model-{{ .Values.model.runId }}
  ports:
    - port: {{ .Values.serving.exposePort }}
      name: {{ .Values.model.runId }}
