apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-{{ .Values.model.runId }}
  namespace: {{ .Values.model.namespace }}
  labels:
    identifier: model-{{ .Values.model.runId }}
  ownerReferences:
    - apiVersion: v1
      controller: true
      kind: Pod
      name: {{ .Values.k8s.ownerPod }}
      uid: {{ .Values.k8s.ownerUID }}